redis:
    image: sameersbn/redis:latest
    ports:
        - 9000:6379
redisBanner:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - 9001:8081