service: aws-nodejs # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline  
functions:
  add-message:
    handler: app/app.AddMessage
    events:
     - http:
         path: add-message
         method: post 
  get-message:
    handler: app/app.getMessage
    events:
     - http:
         path: get-message
         method: get
  update-message:
    handler: app/app.UpdateMessage
    events:
     - http:
         path: update-message/{id}
         method: post
  delete-message:
    handler: app/app.deleteMessage
    events:
     - http:
         path: delete-message/{id}
         method: get
  get-anonymous-user:
    handler: app/app.GetAnonymousUser
    events:
     - http:
         path: get-anonymous-user
         method: get                      
  
  testcase-clear:
    handler: testcase/testcase.clear
    events:
     - http:
         path: testcase-clear
         method: get              
  

  


